### ISSUE TITLE
Bugs in latest code in catarse.js

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2623]
Guys I have found a couple of bugs 

**Rewards from other project is showing up** 

Suppose I have 2 projects and I click on 2 nd project. Then it shows me the rewards from the first project as well plus the header is changed to name from project 1.

While creating a 2nd project, sometimes in the process of editing the project, the project changes to project 1 even if I dont own the project.

**Comment by sushant12** [comment]
issue seem to persist from catarse.js v 1.0.33

**Comment by vicnicius** [comment]
@sushant12 I tried to reproduce this bug in my development environment without luck. Also couldn't in our acceptance environment. Can you provide the specific steps to reproduce it?

**Comment by vicnicius** [comment]
Also, are there any error logs on the browser console?

**Comment by sushant12** [comment]
@vicnicius there are no errors in the browser console

Here is how I reproduced the bug

I cloned a fresh repo of catarse. Connected catarse with fresh new db (not the old one that I am using)

Logged in and created a campaign, say campaign 1 with rewards (reward 1, reward 2). 

Logged out and signed in with a new account. Created a campaign called campaign 2 with rewards (re1, re 2)

I signed out, clicked in campaign 2 and clicked in support this project. After clicking the support this project, I can see the rewards from the campaign 1 and I can also see the name change to campaign 2. It takes like a second or some to change name from campaign 2 to campaign 1.

I then downgraded catarse.js from 1.0.33 to 1.0.32 and the err is non persistent

**Comment by sushant12** [comment]
The other bus is, suppose there are two campaigns (camp1 camp2). While in the process of editing the camp2 , I get redirect to camp 1 edit page. Note that I dont own camp 2. 

In this case, there are no errs in browser console.

**Comment by sushant12** [comment]
@vicnicius were u able to reproduce the bug? I am pretty sure this is an issue. I cloned the catarse project in my other system and the same issues are prevailing.

**Comment by sushant12** [comment]
i can reproduce the issue in catarse.me but i reproduced another issue too. If i open campaign 2 by doing right click and open in new window then the first campaign is shown. All these happens in catarse.js v1.0.33 but not in 1.0.32

**Comment by vicnicius** [comment]
Thank you, @sushant12. I'll work on this.

**Comment by devton** [comment]
@sushant12 @vicnicius i think that i fixed this on the lastest commit before generate the dist 1.0.33 again.

**Comment by sushant12** [comment]
@devton , the issue is still there :(

**Comment by devton** [comment]
@sushant12 Founded now sometimes the currentProject are getting project data on data-parameters that should be used only to provide relation ids, this are making the code fetch without parameters to api and get the first of collection without correct filters.

Can you check again? now i think that is eveything ok.

**Comment by sushant12** [comment]
@devton previously, there was a bug where if I right clciked on the project and opened it in a new window then the first project would show up. I can see that that issue is fixed now. cool

The reward bug is still prevalent.

**Comment by vicnicius** [comment]
@sushant12 @devton I was working on some deploy blocking issues but now I'm done, so tomorrow I'll fix this issue.

**Comment by sushant12** [comment]
fixed on the develop branch
